name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.5.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  very_good_analysis: ^3.0.1
